monitors:
  laptop:
    match:
      - name: eDP-1
    scale: 1

  home-monitor:
    match:
      - name: HDMI-A-1
      - width: 2560
      - height: 1440
    scale: 1
    position: above laptop
    align: center

  work-monitor:
    match:
      - serial: XXXXXXXXXX
    scale: 1
    position: above laptop
    align: center

  projector:
    match:
      - name: HDMI-A-1
      - width: 1920
      - height: 1080
    scale: 1
    position: same-as laptop
